language: node_js
before_script:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
  - npm install -g bower
  - npm build
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
